steps:
  - name: "gcr.io/cloud-builders/gsutil"
    args: ["cp", "gs://aai-environments/relieve/api-env", "./.env"]

  - name: "gcr.io/cloud-builders/gsutil"
    args:
      [
        "cp",
        "gs://aai-environments/relieve/firebase-service-account.json",
        "./storage",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args:
      ["build", "-t", "gcr.io/archisdi/github.com/archisdi/relieve-kern", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/archisdi/github.com/archisdi/relieve-kern"]
